package am.message;

public enum GameUpdate {
    PLAYER_LIST_INIT,
    PLAYER_LIST_ADD,
    PLAYER_LIST_REMOVE,
    PLAYER_CARDS_UPDATE,
    PLAYER_TURN,
    PLAYER_SKIP_TURNS,
    CARDS_STACK_CLEAR,
    CARDS_STACK_ADD,
    WILD_COLOR_SET,
    WILD_COLOR_CLEAR,
    FIRST_CARD,
    CARD_ADD,
    DIRECTION_CHANGE,
    STOP_GAME
}
